name: coderco custom action

description: greet someone

inputs:
  who-to-greet:
    description: who to greet
    required: true
    default: Hello

outputs:
  time:
    description: time greeted

runs:
  using: node24
  main: dist/index.js